In [29]:
import requests
import pandas
from sqlalchemy import create_engine , text
import psycopg2
import os
from dotenv import load_dotenv

load_dotenv()

True

In [ ]:
url = ('https://newsapi.org/v2/everything?'
            'q=Apple&'
            'from=2026-06-10&to=2026-06-11&'
            'sortBy=popularity&'
            f'apiKey={os.getenv('NEWS_API_KEY')}')

response = requests.get(url)
print(response.status_code)

200

In [6]:
data =response.json()
data

{'status': 'ok',
 'totalResults': 2183,
 'articles': [{'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Luke Larsen',
   'title': 'MacOS 27 Golden Gate: Top New Features',
   'description': "Apple has announced the latest version of macOS. It's all about the reintroduction of Siri, which is now accessible from anywhere on the Mac desktop.",
   'url': 'https://www.wired.com/story/macos-27-golden-gate-top-features/',
   'urlToImage': 'https://media.wired.com/photos/6a2849c20d6aa02c6a8cdf9e/191:100/w_1280,c_limit/Apple-OS-27-updates-260608.jpg',
   'publishedAt': '2026-06-09T17:33:21Z',
   'content': 'One of the most interesting new features is Custom Extensions, which lets you create an extension for Safari in natural language. Lastly, the new version of Safari will work the Passwords app to auto… [+2328 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Robert Hart',
   'title': 'Apple wants Europe to blink',
   'description': "It took a few years, but Apple finally made its AI look useful. Now millions of iPhone users in Europe are being told they won't be getting Siri AI anytime soon, if ever - and Apple wants them to blame the EU. Apple says its new AI-powered Siri will not launc…",
   'url': 'https://www.theverge.com/ai-artificial-intelligence/947051/apple-europe-dma-siri-ai',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/STK450_EU_G.jpg?quality=90&strip=all&crop=0%2C9.9676601489831%2C100%2C80.064679702034&w=1200',
   'publishedAt': '2026-06-09T17:13:14Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nApple wants Europe to blink\r\nApple blames DMA for delaying Siri AI in Europe. The EU says nothing is stopping Apple from launching it. \r\nby\r\nRobert HartClose\r\nPo… [+7489 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Stevie Bonifield',
   'title': 'The App Store is going to add subscription bundles soon',
   'description': "Later this year, you will be able to get bundled subscriptions for iPhone apps, as Apple announced it's expanding App Store bundles so they can include offers from different companies. It's similar to streaming video bundles that have combined offers for Appl…",
   'url': 'https://www.theverge.com/tech/947365/apple-subscription-bundles-app-store',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/23925966/acastro_STK045_01.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-09T21:30:48Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nAlong with iOS 27, Apple also announced big changes to the App Store.\r\nAlong with iOS 27, Apple also announced big changes to the App Store.\r\nby\r\nStevie Bonifiel… [+2188 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'David Pierce',
   'title': 'Apple’s best AI idea looks a lot like vibe coding',
   'description': "Most of Apple's current AI ideas are roughly the same as everyone else's AI ideas. A chatbot you can ask questions; quick ways to create or summarize text; bizarre, borderline creepy image-generation tools. The company spent most of its WWDC keynote playing c…",
   'url': 'https://www.theverge.com/tech/946733/apple-shortcuts-ai-safari-tabs-vibe-code',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/AI-Apple-Shortcuts.jpg?quality=90&strip=all&crop=0%2C3.3555449785816%2C100%2C93.288910042837&w=1200',
   'publishedAt': '2026-06-09T13:34:48Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nApples best AI idea looks a lot like vibe coding\r\nSiri AI and Image Playground will get all the hype, but Apple can actually make our lives better in Safari and … [+7449 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'John.Higgins',
   'title': 'The three sets of earbuds I reach for',
   'description': 'I have been an audio reviewer for 20 years. My time as a freelance headphones panelist at Wirecutter, and the multitude of reviews I’ve written for sites like Reviewed, Digital Trends, IGN, and now The Verge, have given me the chance to listen to hundreds of …',
   'url': 'https://www.theverge.com/gadgets/947325/three-earbuds-i-consistently-use',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/268563_go-to_earbuds_JHiggins_0001.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-09T22:21:07Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nEarbuds come and go in the life of a reviewer, but these three have earned permanent spots in my life.\r\nIf you buy something from a Verge link, Vox Media may ear… [+8009 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Allison Johnson',
   'title': 'I tried Siri AI, and so far it actually works',
   'description': 'Parents want one thing, and one thing only, out of AI: to add a list of soccer games or "spirit week" theme days from an email or a poorly formatted flyer onto their calendar in one shot. And I have good news for parents with iPhones - the new Siri can finall…',
   'url': 'https://www.theverge.com/tech/947432/siri-ai-apple-intelligence-ios-27-wwdc',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/DSC03775_processed.jpg?quality=90&strip=all&crop=0%2C10.723165084465%2C100%2C78.55366983107&w=1200',
   'publishedAt': '2026-06-09T23:33:14Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nIts basic, but it works is a big deal.\r\nby\r\nAllison JohnsonClose\r\nPosts from this author will be added to your daily email digest and your homepage feed.\r\nFollow… [+5952 chars]'},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Bruce Gil',
   'title': 'The Apple Car Is Dead, and Waymo Just Bought Its Gravesite',
   'description': 'The robotaxi company paid $220 million for the former proving ground where Apple tested its now dead self-driving car project.',
   'url': 'https://gizmodo.com/the-apple-car-is-dead-and-waymo-just-bought-its-gravesite-2000769695',
   'urlToImage': 'https://gizmodo.com/app/uploads/2026/04/waymo-san-diego-1200x675.jpg',
   'publishedAt': '2026-06-09T22:37:30Z',
   'content': 'Apples self-driving car dream is dead, but its old proving ground will go on testing other self-driving cars.\r\nWaymo, the robotaxi company owned by Alphabet, has acquired the 5,500-acre proving groun… [+2340 chars]'},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Kyle Barr',
   'title': 'With iOS 27, Apple Is Creating an AI Gated Community Inside Its Walled Garden',
   'description': 'Welcome to the age of the segregated iPhone ecosystem.',
   'url': 'https://gizmodo.com/with-ios-27-apple-is-creating-an-ai-gated-community-inside-its-walled-garden-2000769406',
   'urlToImage': 'https://gizmodo.com/app/uploads/2025/09/Apple-Iphone-17-Series-Air-46-1200x675.jpg',
   'publishedAt': '2026-06-09T15:30:30Z',
   'content': 'The entire Apple ecosystem is being segregated, dividing users into those who have AI and those who dont have AI. The updates to iOS 27, macOS 27, and watchOS 27 mean some users will be gatekept from… [+4536 chars]'},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Raymond Wong',
   'title': 'Oh, Thank God: iOS 27 Fixes the Liquid Glass Optical Illusion That Broke My Brain',
   'description': 'Sanity prevails.',
   'url': 'https://gizmodo.com/oh-thank-god-ios-27-fixes-the-liquid-glass-optical-illusion-that-broke-my-brain-2000769666',
   'urlToImage': 'https://gizmodo.com/app/uploads/2026/06/ios27-liquid-glass-1200x675.jpg',
   'publishedAt': '2026-06-09T20:32:03Z',
   'content': 'Someone at Apple must have read my rant.\r\nWhen iOS 26 rolled out last September, I reported on an optical illusion caused by the specular highlights in the corners of app icons, revamped with the ref… [+1858 chars]'},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Jen Lennon',
   'title': 'The Winners of the 61st Nebula Awards Are Here',
   'description': "Stephen Graham Jones took home the award for Best Novel for 'The Buffalo Hunter Hunter.'",
   'url': 'https://gizmodo.com/nebula-awards-2025-winners-list-61st-annual-2000769405',
   'urlToImage': 'https://gizmodo.com/app/uploads/2025/12/nebula-awards-logo-1200x675.jpg',
   'publishedAt': '2026-06-09T15:00:43Z',
   'content': 'The nonprofit Science Fiction and Fantasy Writers of America held its 61st annual Nebula Awards over the weekend, celebrating the best sci-fi and fantasy writing from 2025. The awards cover a broad s… [+5460 chars]'},
  {'source': {'id': None, 'name': 'Android Central'},
   'author': 'sanujb6@gmail.com (Sanuj Bhatia) , Sanuj Bhatia',
   'title': "The OnePlus 15 is picking up one of Android's most useful sharing upgrades",
   'description': 'OnePlus 15 becomes the latest Android phone to get support for AirDrop sharing with Apple devices.',
   'url': 'https://www.androidcentral.com/phones/oneplus/oneplus-15-now-rolling-out-airdrop-support',
   'urlToImage': 'https://cdn.mos.cms.futurecdn.net/EVZqUzTveBr5Uz73RDvi4Q-2048-80.jpg',
   'publishedAt': '2026-06-09T15:19:17Z',
   'content': '<ul><li>OnePlus 15 is now receiving AirDrop support through Quick Share, joining Pixel and Galaxy phones.</li><li>The feature lets Android and iPhone users transfer files directly using native AirDro… [+2339 chars]'},
  {'source': {'id': None, 'name': 'Android Central'},
   'author': 'sanujb6@gmail.com (Sanuj Bhatia) , Sanuj Bhatia',
   'title': "I can't believe I'm saying this: Android needs these five iOS 27 features",
   'description': 'Here are the iOS 27 features that would make Android better if Google copied them.',
   'url': 'https://www.androidcentral.com/apps-software/android-os/9-things-android-should-steal-from-ios-27',
   'urlToImage': 'https://cdn.mos.cms.futurecdn.net/xT8aTTunkD6DnrPiLsmhti-2560-80.jpg',
   'publishedAt': '2026-06-09T08:08:00Z',
   'content': "It's that time of the year again. Apple executives took to the stage to announce some new features and additions coming to the iPhone with the upcoming iOS 27 update. While Apple mostly focused on re… [+6811 chars]"},
  {'source': {'id': None, 'name': 'Android Central'},
   'author': 'namerah.saud-fatmi@futurenet.com (Namerah Saud Fatmi) , Namerah Saud Fatmi',
   'title': 'The UAG Metropolis Tracker Card is a slick blend of Bluetooth tracking and MagSafe charging',
   'description': 'The new UAG Metropolis Tracker Card is slicker than a Slim Jim and supports MagSafe wireless charging.',
   'url': 'https://www.androidcentral.com/accessories/uags-first-bluetooth-tracker-supports-magsafe-wireless-charging',
   'urlToImage': 'https://cdn.mos.cms.futurecdn.net/6FMN2GyecNEd8S7cmVMKP3-2560-80.jpg',
   'publishedAt': '2026-06-09T10:10:00Z',
   'content': '(Image credit: Android Central)\r\nJoin Namerah Saud Fatmi as she explores the cool, quirky, and sometimes downright odd world of smartphone accessories, gadgets, and other nerdy toys every week.\r\nUAG,… [+5186 chars]'},
  {'source': {'id': None, 'name': 'MacRumors'},
   'author': 'Hartley Charlton',
   'title': 'Apple Podcasts Gets Video on Mac and Apple TV, Plus New Search Feature',
   'description': 'Apple yesterday announced several improvements to Apple Podcasts, including video podcast playback on macOS and a fully redesigned tvOS app.\n\n\n\n\n\nMac users will gain a new, enhanced video podcast experience in \u200cApple Podcasts\u200c, including Picture in Picture su…',
   'url': 'https://www.macrumors.com/2026/06/09/apple-podcasts-gets-video-on-mac-and-apple-tv/',
   'urlToImage': 'https://images.macrumors.com/t/IUbDJnUsl4oiGiI6bAWPZNTKD_Q=/2250x/article-new/2021/05/Podcasts-Feature.jpg',
   'publishedAt': '2026-06-09T14:40:56Z',
   'content': 'Apple yesterday announced several improvements to Apple Podcasts, including video podcast playback on macOS and a fully redesigned tvOS app.\r\nMac users will gain a new, enhanced video podcast experie… [+998 chars]'},
  {'source': {'id': None, 'name': 'MacRumors'},
   'author': 'Joe Rossignol',
   'title': 'Apple Says iOS 27 Adds These 12 New Features to Your iPhone',
   'description': "iOS 27's key new feature is a more intelligent and personal version of Siri, but the changes go well beyond that. In a press release today, Apple outlined additional enhancements coming across Apple Maps, Find My, Apple Wallet, Apple Music, and more.\n\n\n\n\n\nApp…",
   'url': 'https://www.macrumors.com/2026/06/09/apple-highlights-ios-27-features/',
   'urlToImage': 'https://images.macrumors.com/t/n8yoN_htXb7huLx8h8ldw1v1qEE=/2186x/article-new/2026/06/Apple-Says-iOS-27-Adds-These-12-New-Features-to-Your-iPhone-Feature.jpg',
   'publishedAt': '2026-06-09T16:47:47Z',
   'content': "iOS 27's key new feature is a more intelligent and personal version of Siri, but the changes go well beyond that. In a press release today, Apple outlined additional enhancements coming across Apple … [+3441 chars]"},
  {'source': {'id': None, 'name': 'MacRumors'},
   'author': 'Hartley Charlton',
   'title': 'Apple Photos Finally Gets a Slideshow Maker',
   'description': 'Apple today announced new slideshow features coming to the Photos app, allowing users to play any set of photos and videos as a slideshow.\n\n\n\n\n\nThere are options to set the slide duration, transition style, and music. iOS 27 also lets users save any slideshow…',
   'url': 'https://www.macrumors.com/2026/06/08/apple-photos-finally-gets-a-slideshow-maker/',
   'urlToImage': 'https://images.macrumors.com/t/wLgAAiLwH3el2P4hkJrGBrtRWVY=/2500x/article-new/2025/08/iOS-26-Glass-Photos-Feature.jpg',
   'publishedAt': '2026-06-09T00:04:42Z',
   'content': 'Apple today announced new slideshow features coming to the Photos app, allowing users to play any set of photos and videos as a slideshow.\r\nThere are options to set the slide duration, transition sty… [+549 chars]'},
  {'source': {'id': None, 'name': 'MacRumors'},
   'author': 'Hartley Charlton',
   'title': 'Apple Outlines Major AI and Developer Tool Updates at 2026 Platforms State of the Union',
   'description': 'Apple yesterday held its WWDC 2026 Platforms State of the Union, detailing a wide range of updates to its developer tools and platforms, headlined by a major expansion of the Foundation Models framework.\n\n\n\n\r\n\n\nThe main announcement was free access to Apple F…',
   'url': 'https://www.macrumors.com/2026/06/09/apple-outlines-major-ai-and-developer-tool-updates/',
   'urlToImage': 'https://images.macrumors.com/t/KeOIKisQVjnpaXpV1Bs0BBpWrMo=/1600x/article-new/2026/06/wwdc-2026-swift.jpg',
   'publishedAt': '2026-06-09T11:07:18Z',
   'content': 'Apple yesterday held its WWDC 2026Platforms State of the Union, detailing a wide range of updates to its developer tools and platforms, headlined by a major expansion of the Foundation Models framewo… [+3820 chars]'},
  {'source': {'id': None, 'name': 'MacRumors'},
   'author': 'Hartley Charlton',
   'title': "EU Says Decision Not to Launch Siri AI in Europe Is Apple's Alone",
   'description': "The European Commission has responded to Apple's announcement that Siri AI will not launch in the EU, saying the decision is entirely Apple's and that the company sought an exemption from its legal obligations rather than a compliant solution.\n\n\n\n\n\nCommission…",
   'url': 'https://www.macrumors.com/2026/06/09/eu-says-decision-not-to-launch-siri-ai-in-europe-is-apples/',
   'urlToImage': 'https://images.macrumors.com/t/AMzlHXYCh5f7HOPQwqP7K3rUyXI=/1600x/article-new/2026/06/Siri-AI.jpg',
   'publishedAt': '2026-06-09T14:07:35Z',
   'content': "The European Commission has responded to Apple's announcement that Siri AI will not launch in the EU, saying the decision is entirely Apple's and that the company sought an exemption from its legal o… [+2360 chars]"},
  {'source': {'id': None, 'name': 'MacRumors'},
   'author': 'Tim Hardwick',
   'title': 'iOS 27: Find My App Lets You Hide Location From Others Temporarily',
   'description': 'Apple\'s first iOS 27 developer beta, released on Monday, includes a new feature in the Find My app that lets you temporarily hide your location from select people. \n\n\n\n\n\nA new "Hide Location" option appears in the user\'s Find My card in the People section, un…',
   'url': 'https://www.macrumors.com/2026/06/09/ios-27-find-my-app-hide-location/',
   'urlToImage': 'https://images.macrumors.com/t/U1VxY7K-0R6wawk2k9zEGqtLOzg=/2500x/article-new/2021/01/FindMy-Feature.jpg',
   'publishedAt': '2026-06-09T11:14:53Z',
   'content': 'Apple\'s first iOS 27 developer beta, released on Monday, includes a new feature in the Find My app that lets you temporarily hide your location from select people. \r\nA new "Hide Location" option appe… [+758 chars]'},
  {'source': {'id': None, 'name': 'CNET'},
   'author': 'Macy Meyer',
   'title': "Apple's Cautious AI Strategy Could Have Been Its Smartest Move",
   'description': 'Commentary: Some say Apple is lagging behind in the AI gold rush. I think the company has positioned itself strategically.',
   'url': 'https://www.cnet.com/tech/services-and-software/apple-ai-strategy-wwdc-2026-commentary/',
   'urlToImage': 'https://www.cnet.com/a/img/resize/f8bea8ffc919bfde6e9ed02403400d213bc3d6e4/hub/2026/05/21/71709010-65fa-4068-b989-cc155e8f1280/wwdc26-promo.png?auto=webp&fit=crop&height=675&width=1200',
   'publishedAt': '2026-06-09T09:00:44Z',
   'content': 'You\'ve probably heard someone say something along the lines of, "Apple is losing the AI race" or "Apple\'s AI is lagging." What if being behind on AI was intentional? Or maybe even a winning strategy?… [+5242 chars]'},
  {'source': {'id': None, 'name': 'CNET'},
   'author': 'Macy Meyer',
   'title': "Google's Gemini 3.5 Live Translate Is Built for Real-Life Conversations",
   'description': "Gemini 3.5 Live Translate doesn't wait for one speaker to finish before generating a response.",
   'url': 'https://www.cnet.com/tech/services-and-software/gemini-3-5-live-translation-real-time-multilingual-conversation/',
   'urlToImage': 'https://www.cnet.com/a/img/resize/f8cbb03e31c20ee58d096f6c18e9af58992a9626/hub/2026/06/09/f2586ef0-93ed-4ab0-bf83-55f64d2a3915/screenshot-2026-06-09-at-1-18-00pm.png?auto=webp&fit=crop&height=675&width=1200',
   'publishedAt': '2026-06-09T19:50:38Z',
   'content': 'A new Google AI tool might be able to translate at the speed of actual conversations, allowing you to talk more naturally with someone speaking a different language than you.\r\nGoogle on Tuesday unvei… [+2166 chars]'},
  {'source': {'id': None, 'name': 'CNET'},
   'author': 'Katelyn Chedraoui',
   'title': "Anthropic's Claude Fable 5 Is the First Mythos-Level AI Model You Can Actually Use",
   'description': 'If you want to test out Fable 5 without paying extra, you need to try it before the end of the month.',
   'url': 'https://www.cnet.com/tech/services-and-software/claude-fable-5-first-mythos-ai-model-anthropic-safety-news/',
   'urlToImage': 'https://www.cnet.com/a/img/resize/3d526f127b727c1cfe7c789bff612a07df4d4b67/hub/2026/04/16/8b393bf3-e54a-47da-9dd7-b5429ce4ff03/anthropic-claude-logo-gettyimages-2269811684.jpg?auto=webp&fit=crop&height=675&width=1200',
   'publishedAt': '2026-06-09T20:25:59Z',
   'content': "AI enthusiasts have been aflutter since rumors first leaked in April about Anthropic's Claude Mythos Preview -- an AI model that the company claimed\xa0could sniff out so many cybersecurity vulnerabilit… [+4136 chars]"},
  {'source': {'id': None, 'name': 'MacRumors'},
   'author': 'Juli Clover',
   'title': 'Telegram Gets Native Apple Watch App',

In [8]:
articles = data['articles']
articles

[{'source': {'id': 'wired', 'name': 'Wired'},
  'author': 'Luke Larsen',
  'title': 'MacOS 27 Golden Gate: Top New Features',
  'description': "Apple has announced the latest version of macOS. It's all about the reintroduction of Siri, which is now accessible from anywhere on the Mac desktop.",
  'url': 'https://www.wired.com/story/macos-27-golden-gate-top-features/',
  'urlToImage': 'https://media.wired.com/photos/6a2849c20d6aa02c6a8cdf9e/191:100/w_1280,c_limit/Apple-OS-27-updates-260608.jpg',
  'publishedAt': '2026-06-09T17:33:21Z',
  'content': 'One of the most interesting new features is Custom Extensions, which lets you create an extension for Safari in natural language. Lastly, the new version of Safari will work the Passwords app to auto… [+2328 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Robert Hart',
  'title': 'Apple wants Europe to blink',
  'description': "It took a few years, but Apple finally made its AI look useful. Now millions of iPhone users in Europe are being told they won't be getting Siri AI anytime soon, if ever - and Apple wants them to blame the EU. Apple says its new AI-powered Siri will not launc…",
  'url': 'https://www.theverge.com/ai-artificial-intelligence/947051/apple-europe-dma-siri-ai',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/STK450_EU_G.jpg?quality=90&strip=all&crop=0%2C9.9676601489831%2C100%2C80.064679702034&w=1200',
  'publishedAt': '2026-06-09T17:13:14Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nApple wants Europe to blink\r\nApple blames DMA for delaying Siri AI in Europe. The EU says nothing is stopping Apple from launching it. \r\nby\r\nRobert HartClose\r\nPo… [+7489 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Stevie Bonifield',
  'title': 'The App Store is going to add subscription bundles soon',
  'description': "Later this year, you will be able to get bundled subscriptions for iPhone apps, as Apple announced it's expanding App Store bundles so they can include offers from different companies. It's similar to streaming video bundles that have combined offers for Appl…",
  'url': 'https://www.theverge.com/tech/947365/apple-subscription-bundles-app-store',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/23925966/acastro_STK045_01.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
  'publishedAt': '2026-06-09T21:30:48Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nAlong with iOS 27, Apple also announced big changes to the App Store.\r\nAlong with iOS 27, Apple also announced big changes to the App Store.\r\nby\r\nStevie Bonifiel… [+2188 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'David Pierce',
  'title': 'Apple’s best AI idea looks a lot like vibe coding',
  'description': "Most of Apple's current AI ideas are roughly the same as everyone else's AI ideas. A chatbot you can ask questions; quick ways to create or summarize text; bizarre, borderline creepy image-generation tools. The company spent most of its WWDC keynote playing c…",
  'url': 'https://www.theverge.com/tech/946733/apple-shortcuts-ai-safari-tabs-vibe-code',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/AI-Apple-Shortcuts.jpg?quality=90&strip=all&crop=0%2C3.3555449785816%2C100%2C93.288910042837&w=1200',
  'publishedAt': '2026-06-09T13:34:48Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nApples best AI idea looks a lot like vibe coding\r\nSiri AI and Image Playground will get all the hype, but Apple can actually make our lives better in Safari and … [+7449 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'John.Higgins',
  'title': 'The three sets of earbuds I reach for',
  'description': 'I have been an audio reviewer for 20 years. My time as a freelance headphones panelist at Wirecutter, and the multitude of reviews I’ve written for sites like Reviewed, Digital Trends, IGN, and now The Verge, have given me the chance to listen to hundreds of …',
  'url': 'https://www.theverge.com/gadgets/947325/three-earbuds-i-consistently-use',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/268563_go-to_earbuds_JHiggins_0001.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
  'publishedAt': '2026-06-09T22:21:07Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nEarbuds come and go in the life of a reviewer, but these three have earned permanent spots in my life.\r\nIf you buy something from a Verge link, Vox Media may ear… [+8009 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Allison Johnson',
  'title': 'I tried Siri AI, and so far it actually works',
  'description': 'Parents want one thing, and one thing only, out of AI: to add a list of soccer games or "spirit week" theme days from an email or a poorly formatted flyer onto their calendar in one shot. And I have good news for parents with iPhones - the new Siri can finall…',
  'url': 'https://www.theverge.com/tech/947432/siri-ai-apple-intelligence-ios-27-wwdc',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/DSC03775_processed.jpg?quality=90&strip=all&crop=0%2C10.723165084465%2C100%2C78.55366983107&w=1200',
  'publishedAt': '2026-06-09T23:33:14Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nIts basic, but it works is a big deal.\r\nby\r\nAllison JohnsonClose\r\nPosts from this author will be added to your daily email digest and your homepage feed.\r\nFollow… [+5952 chars]'},
 {'source': {'id': None, 'name': 'Gizmodo.com'},
  'author': 'Bruce Gil',
  'title': 'The Apple Car Is Dead, and Waymo Just Bought Its Gravesite',
  'description': 'The robotaxi company paid $220 million for the former proving ground where Apple tested its now dead self-driving car project.',
  'url': 'https://gizmodo.com/the-apple-car-is-dead-and-waymo-just-bought-its-gravesite-2000769695',
  'urlToImage': 'https://gizmodo.com/app/uploads/2026/04/waymo-san-diego-1200x675.jpg',
  'publishedAt': '2026-06-09T22:37:30Z',
  'content': 'Apples self-driving car dream is dead, but its old proving ground will go on testing other self-driving cars.\r\nWaymo, the robotaxi company owned by Alphabet, has acquired the 5,500-acre proving groun… [+2340 chars]'},
 {'source': {'id': None, 'name': 'Gizmodo.com'},
  'author': 'Kyle Barr',
  'title': 'With iOS 27, Apple Is Creating an AI Gated Community Inside Its Walled Garden',
  'description': 'Welcome to the age of the segregated iPhone ecosystem.',
  'url': 'https://gizmodo.com/with-ios-27-apple-is-creating-an-ai-gated-community-inside-its-walled-garden-2000769406',
  'urlToImage': 'https://gizmodo.com/app/uploads/2025/09/Apple-Iphone-17-Series-Air-46-1200x675.jpg',
  'publishedAt': '2026-06-09T15:30:30Z',
  'content': 'The entire Apple ecosystem is being segregated, dividing users into those who have AI and those who dont have AI. The updates to iOS 27, macOS 27, and watchOS 27 mean some users will be gatekept from… [+4536 chars]'},
 {'source': {'id': None, 'name': 'Gizmodo.com'},
  'author': 'Raymond Wong',
  'title': 'Oh, Thank God: iOS 27 Fixes the Liquid Glass Optical Illusion That Broke My Brain',
  'description': 'Sanity prevails.',
  'url': 'https://gizmodo.com/oh-thank-god-ios-27-fixes-the-liquid-glass-optical-illusion-that-broke-my-brain-2000769666',
  'urlToImage': 'https://gizmodo.com/app/uploads/2026/06/ios27-liquid-glass-1200x675.jpg',
  'publishedAt': '2026-06-09T20:32:03Z',
  'content': 'Someone at Apple must have read my rant.\r\nWhen iOS 26 rolled out last September, I reported on an optical illusion caused by the specular highlights in the corners of app icons, revamped with the ref… [+1858 chars]'},
 {'source': {'id': None, 'name': 'Gizmodo.com'},
  'author': 'Jen Lennon',
  'title': 'The Winners of the 61st Nebula Awards Are Here',
  'description': "Stephen Graham Jones took home the award for Best Novel for 'The Buffalo Hunter Hunter.'",
  'url': 'https://gizmodo.com/nebula-awards-2025-winners-list-61st-annual-2000769405',
  'urlToImage': 'https://gizmodo.com/app/uploads/2025/12/nebula-awards-logo-1200x675.jpg',
  'publishedAt': '2026-06-09T15:00:43Z',
  'content': 'The nonprofit Science Fiction and Fantasy Writers of America held its 61st annual Nebula Awards over the weekend, celebrating the best sci-fi and fantasy writing from 2025. The awards cover a broad s… [+5460 chars]'},
 {'source': {'id': None, 'name': 'Android Central'},
  'author': 'sanujb6@gmail.com (Sanuj Bhatia) , Sanuj Bhatia',
  'title': "The OnePlus 15 is picking up one of Android's most useful sharing upgrades",
  'description': 'OnePlus 15 becomes the latest Android phone to get support for AirDrop sharing with Apple devices.',
  'url': 'https://www.androidcentral.com/phones/oneplus/oneplus-15-now-rolling-out-airdrop-support',
  'urlToImage': 'https://cdn.mos.cms.futurecdn.net/EVZqUzTveBr5Uz73RDvi4Q-2048-80.jpg',
  'publishedAt': '2026-06-09T15:19:17Z',
  'content': '<ul><li>OnePlus 15 is now receiving AirDrop support through Quick Share, joining Pixel and Galaxy phones.</li><li>The feature lets Android and iPhone users transfer files directly using native AirDro… [+2339 chars]'},
 {'source': {'id': None, 'name': 'Android Central'},
  'author': 'sanujb6@gmail.com (Sanuj Bhatia) , Sanuj Bhatia',
  'title': "I can't believe I'm saying this: Android needs these five iOS 27 features",
  'description': 'Here are the iOS 27 features that would make Android better if Google copied them.',
  'url': 'https://www.androidcentral.com/apps-software/android-os/9-things-android-should-steal-from-ios-27',
  'urlToImage': 'https://cdn.mos.cms.futurecdn.net/xT8aTTunkD6DnrPiLsmhti-2560-80.jpg',
  'publishedAt': '2026-06-09T08:08:00Z',
  'content': "It's that time of the year again. Apple executives took to the stage to announce some new features and additions coming to the iPhone with the upcoming iOS 27 update. While Apple mostly focused on re… [+6811 chars]"},
 {'source': {'id': None, 'name': 'Android Central'},
  'author': 'namerah.saud-fatmi@futurenet.com (Namerah Saud Fatmi) , Namerah Saud Fatmi',
  'title': 'The UAG Metropolis Tracker Card is a slick blend of Bluetooth tracking and MagSafe charging',
  'description': 'The new UAG Metropolis Tracker Card is slicker than a Slim Jim and supports MagSafe wireless charging.',
  'url': 'https://www.androidcentral.com/accessories/uags-first-bluetooth-tracker-supports-magsafe-wireless-charging',
  'urlToImage': 'https://cdn.mos.cms.futurecdn.net/6FMN2GyecNEd8S7cmVMKP3-2560-80.jpg',
  'publishedAt': '2026-06-09T10:10:00Z',
  'content': '(Image credit: Android Central)\r\nJoin Namerah Saud Fatmi as she explores the cool, quirky, and sometimes downright odd world of smartphone accessories, gadgets, and other nerdy toys every week.\r\nUAG,… [+5186 chars]'},
 {'source': {'id': None, 'name': 'MacRumors'},
  'author': 'Hartley Charlton',
  'title': 'Apple Podcasts Gets Video on Mac and Apple TV, Plus New Search Feature',
  'description': 'Apple yesterday announced several improvements to Apple Podcasts, including video podcast playback on macOS and a fully redesigned tvOS app.\n\n\n\n\n\nMac users will gain a new, enhanced video podcast experience in \u200cApple Podcasts\u200c, including Picture in Picture su…',
  'url': 'https://www.macrumors.com/2026/06/09/apple-podcasts-gets-video-on-mac-and-apple-tv/',
  'urlToImage': 'https://images.macrumors.com/t/IUbDJnUsl4oiGiI6bAWPZNTKD_Q=/2250x/article-new/2021/05/Podcasts-Feature.jpg',
  'publishedAt': '2026-06-09T14:40:56Z',
  'content': 'Apple yesterday announced several improvements to Apple Podcasts, including video podcast playback on macOS and a fully redesigned tvOS app.\r\nMac users will gain a new, enhanced video podcast experie… [+998 chars]'},
 {'source': {'id': None, 'name': 'MacRumors'},
  'author': 'Joe Rossignol',
  'title': 'Apple Says iOS 27 Adds These 12 New Features to Your iPhone',
  'description': "iOS 27's key new feature is a more intelligent and personal version of Siri, but the changes go well beyond that. In a press release today, Apple outlined additional enhancements coming across Apple Maps, Find My, Apple Wallet, Apple Music, and more.\n\n\n\n\n\nApp…",
  'url': 'https://www.macrumors.com/2026/06/09/apple-highlights-ios-27-features/',
  'urlToImage': 'https://images.macrumors.com/t/n8yoN_htXb7huLx8h8ldw1v1qEE=/2186x/article-new/2026/06/Apple-Says-iOS-27-Adds-These-12-New-Features-to-Your-iPhone-Feature.jpg',
  'publishedAt': '2026-06-09T16:47:47Z',
  'content': "iOS 27's key new feature is a more intelligent and personal version of Siri, but the changes go well beyond that. In a press release today, Apple outlined additional enhancements coming across Apple … [+3441 chars]"},
 {'source': {'id': None, 'name': 'MacRumors'},
  'author': 'Hartley Charlton',
  'title': 'Apple Photos Finally Gets a Slideshow Maker',
  'description': 'Apple today announced new slideshow features coming to the Photos app, allowing users to play any set of photos and videos as a slideshow.\n\n\n\n\n\nThere are options to set the slide duration, transition style, and music. iOS 27 also lets users save any slideshow…',
  'url': 'https://www.macrumors.com/2026/06/08/apple-photos-finally-gets-a-slideshow-maker/',
  'urlToImage': 'https://images.macrumors.com/t/wLgAAiLwH3el2P4hkJrGBrtRWVY=/2500x/article-new/2025/08/iOS-26-Glass-Photos-Feature.jpg',
  'publishedAt': '2026-06-09T00:04:42Z',
  'content': 'Apple today announced new slideshow features coming to the Photos app, allowing users to play any set of photos and videos as a slideshow.\r\nThere are options to set the slide duration, transition sty… [+549 chars]'},
 {'source': {'id': None, 'name': 'MacRumors'},
  'author': 'Hartley Charlton',
  'title': 'Apple Outlines Major AI and Developer Tool Updates at 2026 Platforms State of the Union',
  'description': 'Apple yesterday held its WWDC 2026 Platforms State of the Union, detailing a wide range of updates to its developer tools and platforms, headlined by a major expansion of the Foundation Models framework.\n\n\n\n\r\n\n\nThe main announcement was free access to Apple F…',
  'url': 'https://www.macrumors.com/2026/06/09/apple-outlines-major-ai-and-developer-tool-updates/',
  'urlToImage': 'https://images.macrumors.com/t/KeOIKisQVjnpaXpV1Bs0BBpWrMo=/1600x/article-new/2026/06/wwdc-2026-swift.jpg',
  'publishedAt': '2026-06-09T11:07:18Z',
  'content': 'Apple yesterday held its WWDC 2026Platforms State of the Union, detailing a wide range of updates to its developer tools and platforms, headlined by a major expansion of the Foundation Models framewo… [+3820 chars]'},
 {'source': {'id': None, 'name': 'MacRumors'},
  'author': 'Hartley Charlton',
  'title': "EU Says Decision Not to Launch Siri AI in Europe Is Apple's Alone",
  'description': "The European Commission has responded to Apple's announcement that Siri AI will not launch in the EU, saying the decision is entirely Apple's and that the company sought an exemption from its legal obligations rather than a compliant solution.\n\n\n\n\n\nCommission…",
  'url': 'https://www.macrumors.com/2026/06/09/eu-says-decision-not-to-launch-siri-ai-in-europe-is-apples/',
  'urlToImage': 'https://images.macrumors.com/t/AMzlHXYCh5f7HOPQwqP7K3rUyXI=/1600x/article-new/2026/06/Siri-AI.jpg',
  'publishedAt': '2026-06-09T14:07:35Z',
  'content': "The European Commission has responded to Apple's announcement that Siri AI will not launch in the EU, saying the decision is entirely Apple's and that the company sought an exemption from its legal o… [+2360 chars]"},
 {'source': {'id': None, 'name': 'MacRumors'},
  'author': 'Tim Hardwick',
  'title': 'iOS 27: Find My App Lets You Hide Location From Others Temporarily',
  'description': 'Apple\'s first iOS 27 developer beta, released on Monday, includes a new feature in the Find My app that lets you temporarily hide your location from select people. \n\n\n\n\n\nA new "Hide Location" option appears in the user\'s Find My card in the People section, un…',
  'url': 'https://www.macrumors.com/2026/06/09/ios-27-find-my-app-hide-location/',
  'urlToImage': 'https://images.macrumors.com/t/U1VxY7K-0R6wawk2k9zEGqtLOzg=/2500x/article-new/2021/01/FindMy-Feature.jpg',
  'publishedAt': '2026-06-09T11:14:53Z',
  'content': 'Apple\'s first iOS 27 developer beta, released on Monday, includes a new feature in the Find My app that lets you temporarily hide your location from select people. \r\nA new "Hide Location" option appe… [+758 chars]'},
 {'source': {'id': None, 'name': 'CNET'},
  'author': 'Macy Meyer',
  'title': "Apple's Cautious AI Strategy Could Have Been Its Smartest Move",
  'description': 'Commentary: Some say Apple is lagging behind in the AI gold rush. I think the company has positioned itself strategically.',
  'url': 'https://www.cnet.com/tech/services-and-software/apple-ai-strategy-wwdc-2026-commentary/',
  'urlToImage': 'https://www.cnet.com/a/img/resize/f8bea8ffc919bfde6e9ed02403400d213bc3d6e4/hub/2026/05/21/71709010-65fa-4068-b989-cc155e8f1280/wwdc26-promo.png?auto=webp&fit=crop&height=675&width=1200',
  'publishedAt': '2026-06-09T09:00:44Z',
  'content': 'You\'ve probably heard someone say something along the lines of, "Apple is losing the AI race" or "Apple\'s AI is lagging." What if being behind on AI was intentional? Or maybe even a winning strategy?… [+5242 chars]'},
 {'source': {'id': None, 'name': 'CNET'},
  'author': 'Macy Meyer',
  'title': "Google's Gemini 3.5 Live Translate Is Built for Real-Life Conversations",
  'description': "Gemini 3.5 Live Translate doesn't wait for one speaker to finish before generating a response.",
  'url': 'https://www.cnet.com/tech/services-and-software/gemini-3-5-live-translation-real-time-multilingual-conversation/',
  'urlToImage': 'https://www.cnet.com/a/img/resize/f8cbb03e31c20ee58d096f6c18e9af58992a9626/hub/2026/06/09/f2586ef0-93ed-4ab0-bf83-55f64d2a3915/screenshot-2026-06-09-at-1-18-00pm.png?auto=webp&fit=crop&height=675&width=1200',
  'publishedAt': '2026-06-09T19:50:38Z',
  'content': 'A new Google AI tool might be able to translate at the speed of actual conversations, allowing you to talk more naturally with someone speaking a different language than you.\r\nGoogle on Tuesday unvei… [+2166 chars]'},
 {'source': {'id': None, 'name': 'CNET'},
  'author': 'Katelyn Chedraoui',
  'title': "Anthropic's Claude Fable 5 Is the First Mythos-Level AI Model You Can Actually Use",
  'description': 'If you want to test out Fable 5 without paying extra, you need to try it before the end of the month.',
  'url': 'https://www.cnet.com/tech/services-and-software/claude-fable-5-first-mythos-ai-model-anthropic-safety-news/',
  'urlToImage': 'https://www.cnet.com/a/img/resize/3d526f127b727c1cfe7c789bff612a07df4d4b67/hub/2026/04/16/8b393bf3-e54a-47da-9dd7-b5429ce4ff03/anthropic-claude-logo-gettyimages-2269811684.jpg?auto=webp&fit=crop&height=675&width=1200',
  'publishedAt': '2026-06-09T20:25:59Z',
  'content': "AI enthusiasts have been aflutter since rumors first leaked in April about Anthropic's Claude Mythos Preview -- an AI model that the company claimed\xa0could sniff out so many cybersecurity vulnerabilit… [+4136 chars]"},
 {'source': {'id': None, 'name': 'MacRumors'},
  'author': 'Juli Clover',
  'title': 'Telegram Gets Native Apple Watch App',
  'description': 'Messaging app Telegram now has a native Apple Watch app. The app supports viewing and responding to Telegram messages from the wrist.\n\n\n\n\n\nFeatures like stickers, voice messages, and location information can be shared from the Apple Watch app.\n\n\n\nTelegram had…',
  'url': 'https://www.macrumors.com/2026/06/09/telegram-apple-watch-app/',

In [12]:
import pandas as pd
articles_df=pd.DataFrame(articles)
articles_df.head()

,source,author,title,description,url,urlToImage,publishedAt,content
0,"{'id': 'wired', 'name': 'Wired'}",Luke Larsen,MacOS 27 Golden Gate: Top New Features,Apple has announced the latest version of macO...,https://www.wired.com/story/macos-27-golden-ga...,https://media.wired.com/photos/6a2849c20d6aa02...,2026-06-09T17:33:21Z,One of the most interesting new features is Cu...
1,"{'id': 'the-verge', 'name': 'The Verge'}",Robert Hart,Apple wants Europe to blink,"It took a few years, but Apple finally made it...",https://www.theverge.com/ai-artificial-intelli...,https://platform.theverge.com/wp-content/uploa...,2026-06-09T17:13:14Z,<ul><li></li><li></li><li></li></ul>\r\nApple ...
2,"{'id': 'the-verge', 'name': 'The Verge'}",Stevie Bonifield,The App Store is going to add subscription bun...,"Later this year, you will be able to get bundl...",https://www.theverge.com/tech/947365/apple-sub...,https://platform.theverge.com/wp-content/uploa...,2026-06-09T21:30:48Z,<ul><li></li><li></li><li></li></ul>\r\nAlong ...
3,"{'id': 'the-verge', 'name': 'The Verge'}",David Pierce,Apple’s best AI idea looks a lot like vibe coding,Most of Apple's current AI ideas are roughly t...,https://www.theverge.com/tech/946733/apple-sho...,https://platform.theverge.com/wp-content/uploa...,2026-06-09T13:34:48Z,<ul><li></li><li></li><li></li></ul>\r\nApples...
4,"{'id': 'the-verge', 'name': 'The Verge'}",John.Higgins,The three sets of earbuds I reach for,I have been an audio reviewer for 20 years. My...,https://www.theverge.com/gadgets/947325/three-...,https://platform.theverge.com/wp-content/uploa...,2026-06-09T22:21:07Z,<ul><li></li><li></li><li></li></ul>\r\nEarbud...

In [13]:
articles_df['content']

0     One of the most interesting new features is Cu...
1     <ul><li></li><li></li><li></li></ul>\r\nApple ...
2     <ul><li></li><li></li><li></li></ul>\r\nAlong ...
3     <ul><li></li><li></li><li></li></ul>\r\nApples...
4     <ul><li></li><li></li><li></li></ul>\r\nEarbud...
                            ...
92    macOS 27 includes several additions and improv...
93    Ahead of yesterday’s keynote, we asked you how...
94    Apple yesterday announced that Siri AI will no...
95    Among the new features in macOS 27 Golden Gate...
96    iOS 27 is officially here, available now in be...
Name: content, Length: 97, dtype: str

In [14]:
articles_df=articles_df.drop(columns=['source','urlToImage'])
articles_df.head()

,author,title,description,url,publishedAt,content
0,Luke Larsen,MacOS 27 Golden Gate: Top New Features,Apple has announced the latest version of macO...,https://www.wired.com/story/macos-27-golden-ga...,2026-06-09T17:33:21Z,One of the most interesting new features is Cu...
1,Robert Hart,Apple wants Europe to blink,"It took a few years, but Apple finally made it...",https://www.theverge.com/ai-artificial-intelli...,2026-06-09T17:13:14Z,<ul><li></li><li></li><li></li></ul>\r\nApple ...
2,Stevie Bonifield,The App Store is going to add subscription bun...,"Later this year, you will be able to get bundl...",https://www.theverge.com/tech/947365/apple-sub...,2026-06-09T21:30:48Z,<ul><li></li><li></li><li></li></ul>\r\nAlong ...
3,David Pierce,Apple’s best AI idea looks a lot like vibe coding,Most of Apple's current AI ideas are roughly t...,https://www.theverge.com/tech/946733/apple-sho...,2026-06-09T13:34:48Z,<ul><li></li><li></li><li></li></ul>\r\nApples...
4,John.Higgins,The three sets of earbuds I reach for,I have been an audio reviewer for 20 years. My...,https://www.theverge.com/gadgets/947325/three-...,2026-06-09T22:21:07Z,<ul><li></li><li></li><li></li></ul>\r\nEarbud...

In [15]:
articles_df.rename(columns={'publishedAt':'published_at'}, inplace=True)
articles_df.head()

,author,title,description,url,published_at,content
0,Luke Larsen,MacOS 27 Golden Gate: Top New Features,Apple has announced the latest version of macO...,https://www.wired.com/story/macos-27-golden-ga...,2026-06-09T17:33:21Z,One of the most interesting new features is Cu...
1,Robert Hart,Apple wants Europe to blink,"It took a few years, but Apple finally made it...",https://www.theverge.com/ai-artificial-intelli...,2026-06-09T17:13:14Z,<ul><li></li><li></li><li></li></ul>\r\nApple ...
2,Stevie Bonifield,The App Store is going to add subscription bun...,"Later this year, you will be able to get bundl...",https://www.theverge.com/tech/947365/apple-sub...,2026-06-09T21:30:48Z,<ul><li></li><li></li><li></li></ul>\r\nAlong ...
3,David Pierce,Apple’s best AI idea looks a lot like vibe coding,Most of Apple's current AI ideas are roughly t...,https://www.theverge.com/tech/946733/apple-sho...,2026-06-09T13:34:48Z,<ul><li></li><li></li><li></li></ul>\r\nApples...
4,John.Higgins,The three sets of earbuds I reach for,I have been an audio reviewer for 20 years. My...,https://www.theverge.com/gadgets/947325/three-...,2026-06-09T22:21:07Z,<ul><li></li><li></li><li></li></ul>\r\nEarbud...

In [ ]:
DATABASE_NAME = os.getenv('DATABASE_NAME')
DATABASE_USER = os.getenv('DATABASE_USER')
DATABASE_PORT = os.getenv('DATABASE_PORT')
DATABASE_PASSWORD = os.getenv('DATABASE_PASSWORD')
DATABASE_HOST = os.getenv('DATABASE_HOST')

engine = create_engine(f'postgresql+psycopg2://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}')

In [26]:
with engine.connect() as conn:
    resort = conn.execute(text('select * from articles;'))
    for i in resort:
        print(i)

('Luke Larsen', 'MacOS 27 Golden Gate: Top New Features', "Apple has announced the latest version of macOS. It's all about the reintroduction of Siri, which is now accessible from anywhere on the Mac desktop.", 'https://www.wired.com/story/macos-27-golden-gate-top-features/', '2026-06-09T17:33:21Z', 'One of the most interesting new features is Custom Extensions, which lets you create an extension for Safari in natural language. Lastly, the new version of Safari will work the Passwords app to auto… [+2328 chars]')
('Robert Hart', 'Apple wants Europe to blink', "It took a few years, but Apple finally made its AI look useful. Now millions of iPhone users in Europe are being told they won't be getting Siri AI anytime soon, if ever - and Apple wants them to blame the EU. Apple says its new AI-powered Siri will not launc…", 'https://www.theverge.com/ai-artificial-intelligence/947051/apple-europe-dma-siri-ai', '2026-06-09T17:13:14Z', '<ul><li></li><li></li><li></li></ul>\r\nApple wants Europe to blink\r\nApple blames DMA for delaying Siri AI in Europe. The EU says nothing is stopping Apple from launching it. \r\nby\r\nRobert HartClose\r\nPo… [+7489 chars]')
('Stevie Bonifield', 'The App Store is going to add subscription bundles soon', "Later this year, you will be able to get bundled subscriptions for iPhone apps, as Apple announced it's expanding App Store bundles so they can include offers from different companies. It's similar to streaming video bundles that have combined offers for Appl…", 'https://www.theverge.com/tech/947365/apple-subscription-bundles-app-store', '2026-06-09T21:30:48Z', '<ul><li></li><li></li><li></li></ul>\r\nAlong with iOS 27, Apple also announced big changes to the App Store.\r\nAlong with iOS 27, Apple also announced big changes to the App Store.\r\nby\r\nStevie Bonifiel… [+2188 chars]')
('David Pierce', 'Apple’s best AI idea looks a lot like vibe coding', "Most of Apple's current AI ideas are roughly the same as everyone else's AI ideas. A chatbot you can ask questions; quick ways to create or summarize text; bizarre, borderline creepy image-generation tools. The company spent most of its WWDC keynote playing c…", 'https://www.theverge.com/tech/946733/apple-shortcuts-ai-safari-tabs-vibe-code', '2026-06-09T13:34:48Z', '<ul><li></li><li></li><li></li></ul>\r\nApples best AI idea looks a lot like vibe coding\r\nSiri AI and Image Playground will get all the hype, but Apple can actually make our lives better in Safari and … [+7449 chars]')
('John.Higgins', 'The three sets of earbuds I reach for', 'I have been an audio reviewer for 20 years. My time as a freelance headphones panelist at Wirecutter, and the multitude of reviews I’ve written for sites like Reviewed, Digital Trends, IGN, and now The Verge, have given me the chance to listen to hundreds of …', 'https://www.theverge.com/gadgets/947325/three-earbuds-i-consistently-use', '2026-06-09T22:21:07Z', '<ul><li></li><li></li><li></li></ul>\r\nEarbuds come and go in the life of a reviewer, but these three have earned permanent spots in my life.\r\nIf you buy something from a Verge link, Vox Media may ear… [+8009 chars]')
('Allison Johnson', 'I tried Siri AI, and so far it actually works', 'Parents want one thing, and one thing only, out of AI: to add a list of soccer games or "spirit week" theme days from an email or a poorly formatted flyer onto their calendar in one shot. And I have good news for parents with iPhones - the new Siri can finall…', 'https://www.theverge.com/tech/947432/siri-ai-apple-intelligence-ios-27-wwdc', '2026-06-09T23:33:14Z', '<ul><li></li><li></li><li></li></ul>\r\nIts basic, but it works is a big deal.\r\nby\r\nAllison JohnsonClose\r\nPosts from this author will be added to your daily email digest and your homepage feed.\r\nFollow… [+5952 chars]')
('Bruce Gil', 'The Apple Car Is Dead, and Waymo Just Bought Its Gravesite', 'The robotaxi company paid $220 million for the former proving ground where Apple tested its now dead self-driving car project.', 'https://gizmodo.com/the-apple-car-is-dead-and-waymo-just-bought-its-gravesite-2000769695', '2026-06-09T22:37:30Z', 'Apples self-driving car dream is dead, but its old proving ground will go on testing other self-driving cars.\r\nWaymo, the robotaxi company owned by Alphabet, has acquired the 5,500-acre proving groun… [+2340 chars]')
('Kyle Barr', 'With iOS 27, Apple Is Creating an AI Gated Community Inside Its Walled Garden', 'Welcome to the age of the segregated iPhone ecosystem.', 'https://gizmodo.com/with-ios-27-apple-is-creating-an-ai-gated-community-inside-its-walled-garden-2000769406', '2026-06-09T15:30:30Z', 'The entire Apple ecosystem is being segregated, dividing users into those who have AI and those who dont have AI. The updates to iOS 27, macOS 27, and watchOS 27 mean some users will be gatekept from… [+4536 chars]')
('Raymond Wong', 'Oh, Thank God: iOS 27 Fixes the Liquid Glass Optical Illusion That Broke My Brain', 'Sanity prevails.', 'https://gizmodo.com/oh-thank-god-ios-27-fixes-the-liquid-glass-optical-illusion-that-broke-my-brain-2000769666', '2026-06-09T20:32:03Z', 'Someone at Apple must have read my rant.\r\nWhen iOS 26 rolled out last September, I reported on an optical illusion caused by the specular highlights in the corners of app icons, revamped with the ref… [+1858 chars]')
('Jen Lennon', 'The Winners of the 61st Nebula Awards Are Here', "Stephen Graham Jones took home the award for Best Novel for 'The Buffalo Hunter Hunter.'", 'https://gizmodo.com/nebula-awards-2025-winners-list-61st-annual-2000769405', '2026-06-09T15:00:43Z', 'The nonprofit Science Fiction and Fantasy Writers of America held its 61st annual Nebula Awards over the weekend, celebrating the best sci-fi and fantasy writing from 2025. The awards cover a broad s… [+5460 chars]')
('sanujb6@gmail.com (Sanuj Bhatia) , Sanuj Bhatia', "The OnePlus 15 is picking up one of Android's most useful sharing upgrades", 'OnePlus 15 becomes the latest Android phone to get support for AirDrop sharing with Apple devices.', 'https://www.androidcentral.com/phones/oneplus/oneplus-15-now-rolling-out-airdrop-support', '2026-06-09T15:19:17Z', '<ul><li>OnePlus 15 is now receiving AirDrop support through Quick Share, joining Pixel and Galaxy phones.</li><li>The feature lets Android and iPhone users transfer files directly using native AirDro… [+2339 chars]')
('sanujb6@gmail.com (Sanuj Bhatia) , Sanuj Bhatia', "I can't believe I'm saying this: Android needs these five iOS 27 features", 'Here are the iOS 27 features that would make Android better if Google copied them.', 'https://www.androidcentral.com/apps-software/android-os/9-things-android-should-steal-from-ios-27', '2026-06-09T08:08:00Z', "It's that time of the year again. Apple executives took to the stage to announce some new features and additions coming to the iPhone with the upcoming iOS 27 update. While Apple mostly focused on re… [+6811 chars]")
('namerah.saud-fatmi@futurenet.com (Namerah Saud Fatmi) , Namerah Saud Fatmi', 'The UAG Metropolis Tracker Card is a slick blend of Bluetooth tracking and MagSafe charging', 'The new UAG Metropolis Tracker Card is slicker than a Slim Jim and supports MagSafe wireless charging.', 'https://www.androidcentral.com/accessories/uags-first-bluetooth-tracker-supports-magsafe-wireless-charging', '2026-06-09T10:10:00Z', '(Image credit: Android Central)\r\nJoin Namerah Saud Fatmi as she explores the cool, quirky, and sometimes downright odd world of smartphone accessories, gadgets, and other nerdy toys every week.\r\nUAG,… [+5186 chars]')
('Hartley Charlton', 'Apple Podcasts Gets Video on Mac and Apple TV, Plus New Search Feature', 'Apple yesterday announced several improvements to Apple Podcasts, including video podcast playback on macOS and a fully redesigned tvOS app.\n\n\n\n\n\nMac users will gain a new, enhanced video podcast experience in \u200cApple Podcasts\u200c, including Picture in Picture su…', 'https://www.macrumors.com/2026/06/09/apple-podcasts-gets-video-on-mac-and-apple-tv/', '2026-06-09T14:40:56Z', 'Apple yesterday announced several improvements to Apple Podcasts, including video podcast playback on macOS and a fully redesigned tvOS app.\r\nMac users will gain a new, enhanced video podcast experie… [+998 chars]')
('Joe Rossignol', 'Apple Says iOS 27 Adds These 12 New Features to Your iPhone', "iOS 27's key new feature is a more intelligent and personal version of Siri, but the changes go well beyond that. In a press release today, Apple outlined additional enhancements coming across Apple Maps, Find My, Apple Wallet, Apple Music, and more.\n\n\n\n\n\nApp…", 'https://www.macrumors.com/2026/06/09/apple-highlights-ios-27-features/', '2026-06-09T16:47:47Z', "iOS 27's key new feature is a more intelligent and personal version of Siri, but the changes go well beyond that. In a press release today, Apple outlined additional enhancements coming across Apple … [+3441 chars]")
('Hartley Charlton', 'Apple Photos Finally Gets a Slideshow Maker', 'Apple today announced new slideshow features coming to the Photos app, allowing users to play any set of photos and videos as a slideshow.\n\n\n\n\n\nThere are options to set the slide duration, transition style, and music. iOS 27 also lets users save any slideshow…', 'https://www.macrumors.com/2026/06/08/apple-photos-finally-gets-a-slideshow-maker/', '2026-06-09T00:04:42Z', 'Apple today announced new slideshow features coming to the Photos app, allowing users to play any set of photos and videos as a slideshow.\r\nThere are options to set the slide duration, transition sty… [+549 chars]')
('Hartley Charlton', 'Apple Outlines Major AI and Developer Tool Updates at 2026 Platforms State of the Union', 'Apple yesterday held its WWDC 2026 Platforms State of the Union, detailing a wide range of updates to its developer tools and platforms, headlined by a major expansion of the Foundation Models framework.\n\n\n\n\r\n\n\nThe main announcement was free access to Apple F…', 'https://www.macrumors.com/2026/06/09/apple-outlines-major-ai-and-developer-tool-updates/', '2026-06-09T11:07:18Z', 'Apple yesterday held its WWDC 2026Platforms State of the Union, detailing a wide range of updates to its developer tools and platforms, headlined by a major expansion of the Foundation Models framewo… [+3820 chars]')
('Hartley Charlton', "EU Says Decision Not to Launch Siri AI in Europe Is Apple's Alone", "The European Commission has responded to Apple's announcement that Siri AI will not launch in the EU, saying the decision is entirely Apple's and that the company sought an exemption from its legal obligations rather than a compliant solution.\n\n\n\n\n\nCommission…", 'https://www.macrumors.com/2026/06/09/eu-says-decision-not-to-launch-siri-ai-in-europe-is-apples/', '2026-06-09T14:07:35Z', "The European Commission has responded to Apple's announcement that Siri AI will not launch in the EU, saying the decision is entirely Apple's and that the company sought an exemption from its legal o… [+2360 chars]")
('Tim Hardwick', 'iOS 27: Find My App Lets You Hide Location From Others Temporarily', 'Apple\'s first iOS 27 developer beta, released on Monday, includes a new feature in the Find My app that lets you temporarily hide your location from select people. \n\n\n\n\n\nA new "Hide Location" option appears in the user\'s Find My card in the People section, un…', 'https://www.macrumors.com/2026/06/09/ios-27-find-my-app-hide-location/', '2026-06-09T11:14:53Z', 'Apple\'s first iOS 27 developer beta, released on Monday, includes a new feature in the Find My app that lets you temporarily hide your location from select people. \r\nA new "Hide Location" option appe… [+758 chars]')
('Macy Meyer', "Apple's Cautious AI Strategy Could Have Been Its Smartest Move", 'Commentary: Some say Apple is lagging behind in the AI gold rush. I think the company has positioned itself strategically.', 'https://www.cnet.com/tech/services-and-software/apple-ai-strategy-wwdc-2026-commentary/', '2026-06-09T09:00:44Z', 'You\'ve probably heard someone say something along the lines of, "Apple is losing the AI race" or "Apple\'s AI is lagging." What if being behind on AI was intentional? Or maybe even a winning strategy?… [+5242 chars]')
('Macy Meyer', "Google's Gemini 3.5 Live Translate Is Built for Real-Life Conversations", "Gemini 3.5 Live Translate doesn't wait for one speaker to finish before generating a response.", 'https://www.cnet.com/tech/services-and-software/gemini-3-5-live-translation-real-time-multilingual-conversation/', '2026-06-09T19:50:38Z', 'A new Google AI tool might be able to translate at the speed of actual conversations, allowing you to talk more naturally with someone speaking a different language than you.\r\nGoogle on Tuesday unvei… [+2166 chars]')
('Katelyn Chedraoui', "Anthropic's Claude Fable 5 Is the First Mythos-Level AI Model You Can Actually Use", 'If you want to test out Fable 5 without paying extra, you need to try it before the end of the month.', 'https://www.cnet.com/tech/services-and-software/claude-fable-5-first-mythos-ai-model-anthropic-safety-news/', '2026-06-09T20:25:59Z', "AI enthusiasts have been aflutter since rumors first leaked in April about Anthropic's Claude Mythos Preview -- an AI model that the company claimed\xa0could sniff out so many cybersecurity vulnerabilit… [+4136 chars]")
('Juli Clover', 'Telegram Gets Native Apple Watch App', 'Messaging app Telegram now has a native Apple Watch app. The app supports viewing and responding to Telegram messages from the wrist.\n\n\n\n\n\nFeatures like stickers, voice messages, and location information can be shared from the Apple Watch app.\n\n\n\nTelegram had…', 'https://www.macrumors.com/2026/06/09/telegram-apple-watch-app/', '2026-06-09T21:37:31Z', 'Messaging app Telegram now has a native Apple Watch app. The app supports viewing and responding to Telegram messages from the wrist.\r\nFeatures like stickers, voice messages, and location information… [+288 chars]')
('Juli Clover', 'All the Liquid Glass Changes in macOS Golden Gate', 'When Liquid Glass launched in macOS Tahoe, Apple faced criticism over how the design looked on the Mac. Some people felt that Liquid Glass in \u200cmacOS Tahoe\u200c was an afterthought with little impact from the design update, while others had issues with contrast, r…', 'https://www.macrumors.com/2026/06/09/macos-golden-gate-liquid-glass/', '2026-06-09T19:11:35Z', 'When Liquid Glass launched in macOS Tahoe, Apple faced criticism over how the design looked on the Mac. Some people felt that Liquid Glass in \u200cmacOS Tahoe\u200c was an afterthought with little impact from… [+2613 chars]')
('Hartley Charlton', 'macOS 27 Finally Brings Direct Touch Control to Sidecar', 'Apple has added direct touch input to Sidecar with macOS 27 Golden Gate and iPadOS 27, allowing users to tap and interact with macOS interface elements using a finger on their iPad for the first time.\n\n\n\n\n\nPreviously, \u200cSidecar\u200c was deliberately limited as a t…', 'https://www.macrumors.com/2026/06/09/macos-27-brings-direct-touch-control-to-sidecar/', '2026-06-09T16:17:00Z', 'Apple has added direct touch input to Sidecar with macOS 27 Golden Gate and iPadOS 27, allowing users to tap and interact with macOS interface elements using a finger on their iPad for the first time… [+1499 chars]')
('Joe Rossignol', 'Apple Reveals How Many iPhones Were Running iOS 26 Before WWDC', 'Apple has shared updated iOS 26 and iPadOS 26 adoption figures, revealing how many iPhones and iPads were running those software versions on the day before the start of WWDC 2026 and the release of the first iOS 27 developer beta.\n\n\n\n\n\nThese adoption numbers …', 'https://www.macrumors.com/2026/06/09/ios-26-adoption-stats-wwdc/', '2026-06-09T14:30:50Z', 'Apple has shared updated iOS 26 and iPadOS 26 adoption figures, revealing how many iPhones and iPads were running those software versions on the day before the start of WWDC 2026 and the release of t… [+989 chars]')
('Hartley Charlton', 'watchOS 27 Features Dynamic App Grid, New Gesture Control, and More', 'Apple today unveiled watchOS 27, featuring a redesigned dynamic app grid, new gesture controls, and a raft of usability and battery improvements.\n\n\n\n\n\nThe new dynamic app grid surfaces and rearranges five apps based on context and usage. Users can simply tap …', 'https://www.macrumors.com/2026/06/08/watchos-27-features-dynamic-app-grid-new-and-more/', '2026-06-09T00:16:17Z', 'Apple today unveiled watchOS 27, featuring a redesigned dynamic app grid, new gesture controls, and a raft of usability and battery improvements.\r\nThe new dynamic app grid surfaces and rearranges fiv… [+1783 chars]')
('Hartley Charlton', 'watchOS 27 Gains a Consolidated and Redesigned Find My App', 'Apple yesterday announced a redesigned Find My app in watchOS 27 that brings all tracking functionality into a single, map-centric interface.\n\n\n\n\n\nPreviously split across separate Find Devices, Find People, and Find Items apps, the new app now consolidates ev…', 'https://www.macrumors.com/2026/06/09/watchos-27-gains-consolidated-and-redesigned-find-my-app/', '2026-06-09T10:15:29Z', 'Apple yesterday announced a redesigned Find My app in watchOS 27 that brings all tracking functionality into a single, map-centric interface.\r\nPreviously split across separate Find Devices, Find Peop… [+416 chars]')
('Hartley Charlton', 'macOS 27 Golden Gate Adopts iPhone-Like Pull-to-Refresh Support', 'macOS 27 Golden Gate adds pull-to-refresh support to the Mac, adopting one of iPhone and iPad\'s most familiar gestures for the first time.\n\n\n\n\n\nThe feature, which Apple calls "Swipe down to refresh," lets users swipe down within apps to fetch the latest conte…', 'https://www.macrumors.com/2026/06/09/macos-27-golden-gate-pull-to-refresh-support/', '2026-06-09T15:36:36Z', 'macOS 27 Golden Gate adds pull-to-refresh support to the Mac, adopting one of iPhone and iPad\'s most familiar gestures for the first time.\r\nThe feature, which Apple calls "Swipe down to refresh," let… [+888 chars]')
('Hartley Charlton', "Apple's New AI Models Contain 'None' of Google's Gemini Assistant", "Apple executives have detailed the architecture of the company's new Apple Foundation Models (AFM) and clarified exactly how Google's technology factored into their development.\n\n\n\n\n\nCraig Federighi, Apple's SVP of Software Engineering, held a post-keynote te…", 'https://www.macrumors.com/2026/06/09/apples-new-ai-contains-no-gemini/', '2026-06-09T13:46:06Z', "Apple executives have detailed the architecture of the company's new Apple Foundation Models (AFM) and clarified exactly how Google's technology factored into their development.\r\nCraig Federighi, App… [+3695 chars]")
('Tim Hardwick', "iOS 27 Lets You Dismiss the 'Now Playing' Lock Screen Widget", "Apple in iOS 27 has made a small but significant change to how the Now Playing widget works on your iPhone's Lock Screen – you can now swipe it away to get rid of it.\n\n\n\n\n\nPreviously, there was no way to dismiss the Now Playing interface on the Lock Screen. B…", 'https://www.macrumors.com/2026/06/09/ios-27-dismiss-now-playing-lock-screen-widget/', '2026-06-09T11:00:55Z', "Apple in iOS 27 has made a small but significant change to how the Now Playing widget works on your iPhone's Lock Screen you can now swipe it away to get rid of it.\r\nPreviously, there was no way to d… [+969 chars]")

In [25]:
articles_df.to_sql('articles',engine, if_exists='replace', index= False)

97